### ISSUE TITLE
was ist der unterschied zwischen....

### ISSUE THREAD

**Issue by ghost** [janrueth/SiriServerCore#1]
dem server und dem siriserver?
erklär mir bitte mal :)

**Comment by janrueth** [comment]
Wie in der readme von siriServer zu lesen ist, arbeite ich an dem siriServer repository nicht weiter. Dort hat sich zuviel plugin code mit dem server code vermischt. Das hier ist der Teil den ich entwickelt hab und den server kern darstellt. Ich werde in diesem repository keine Plugins aufnehmen sondern nur an der kern struktur arbeiten.
Diese version hier ist eine überarbeitete vom siriServer, sie hat z.b. kein M2Crypto dependency mehr und nutzt nun twisted anstatt asyncore als basis des servers und ist damit deutlich stabiler und skaliert besser.
Die Plugins können weiterhin so verwendet werden wie immer, ich würde empfehlen sie allerdings in ordner zu packen (siehe ExamplePlugin) das ist irgendwie übersichtlicher (wie man die plugins in der plugins.conf angibt ändert sich dadurch nicht)

English:
As you can read in the README of siriServer repo, I discontinue developing with that repository, as the server code got heavily mixed with other stuff. In this repository only the server core is maintained which I developed. This version here is ahead of the siriServer version, it has less dependencies, for example M2Crypto is not needed anymore and we use twisted instead of asyncore as the basis for the server which is more robust and scales better. Plugins can still be used as before but I highly encourage putting them into directories (see the examplePlugin on how to do so) for cleanness (the way to load a plugin via plugins.conf does not change by putting it into a folder)
